// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-7bQ9sIguT4ERhaZPCUhjJvhEoK1xBpA',
    appId: '1:632954893578:web:812b29473e88f6473976f3',
    messagingSenderId: '632954893578',
    projectId: 'sanjaysprojects-a274c',
    authDomain: 'sanjaysprojects-a274c.firebaseapp.com',
    storageBucket: 'sanjaysprojects-a274c.firebasestorage.app',
    measurementId: 'G-3QW4S17HQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Gk5gpiqgzGrxDXszqGboMFXoJwQPk8s',
    appId: '1:632954893578:android:70bff0e109e8079f3976f3',
    messagingSenderId: '632954893578',
    projectId: 'sanjaysprojects-a274c',
    storageBucket: 'sanjaysprojects-a274c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhia5f05Dp-8Vsri844_C0XxfBq8nOqX4',
    appId: '1:632954893578:ios:dce9736be8b67f773976f3',
    messagingSenderId: '632954893578',
    projectId: 'sanjaysprojects-a274c',
    storageBucket: 'sanjaysprojects-a274c.firebasestorage.app',
    iosBundleId: 'com.example.homeMaintananceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhia5f05Dp-8Vsri844_C0XxfBq8nOqX4',
    appId: '1:632954893578:ios:dce9736be8b67f773976f3',
    messagingSenderId: '632954893578',
    projectId: 'sanjaysprojects-a274c',
    storageBucket: 'sanjaysprojects-a274c.firebasestorage.app',
    iosBundleId: 'com.example.homeMaintananceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-7bQ9sIguT4ERhaZPCUhjJvhEoK1xBpA',
    appId: '1:632954893578:web:812b29473e88f6473976f3',
    messagingSenderId: '632954893578',
    projectId: 'sanjaysprojects-a274c',
    authDomain: 'sanjaysprojects-a274c.firebaseapp.com',
    storageBucket: 'sanjaysprojects-a274c.firebasestorage.app',
    measurementId: 'G-3QW4S17HQM',
  );

}